### ISSUE TITLE
REST API update status.

### ISSUE THREAD

**Issue by mkaliyannan** [sijis/whiskerboard#11]
Hey, Thanks man for keepin this project. I am using for my office server status update for my team. Is that anyway make automate via restapi.

Currently I am using zabbix and want to query the status and update via RESTAPI. Do you have any idea how we can do this ?

**Comment by jvasallo** [comment]
@mkaliyannan Did you know about this? https://github.com/sijis/whiskerboard-tools

I think we put an example there.

**Comment by mkaliyannan** [comment]
Cool. Nice work and appreciated . Can we update this tool to Django to latest version ? is that hard ?

**Comment by mkaliyannan** [comment]
I am wondering  is there anyway to put the status bar on any url.

**Comment by sijis** [comment]
@mkaliyannan I haven't touched the code base in a while. I will accept PRs related to using a new django version. The only way I can think of doing so, is to try the app in a new django version and see what errors/warnings you get. My suspicion is that it will mainly work with some minor tweaks.

> I am wondering is there anyway to put the status bar on any url.

I'm not sure what you mean by this. Could you elaborate?

**Comment by sijis** [comment]
@mkaliyannan I just spent some upgrading the code to latest django.
If you are courageous, you can try the current branch `upgrade/django_1.10.5` and see if things work for you. I tested it with python3 on django 1.10.5.

**Comment by mkaliyannan** [comment]
Sure. Thanks . I will let you know
