### ISSUE TITLE
Add advisory type notice

### ISSUE THREAD

**Issue by sijis** [sijis/whiskerboard#7]
There should be a way to add a global notice that is displayed prominently on the status page.

The use case is when there are changes/issues that affect mutiple (or all) services there is 1 notice displayed for this type of message.

**Comment by jvasallo** [comment]
I believe we have two approaches.

We can migrate our existing model and add a boolean value, such as is_global, these global messages will then aggregate at the top of the page in some pretty format.

Alternatively, we can create a table just for global messages and they shall have the fields similar to a regular message with the exception of active or inactive. Active means display, inactive means just store but don't display.

What do you think? What did you have in mind. All in all this feature request is pretty simple. :-)

**Comment by sijis** [comment]
Im thinking the latter.

otherwise we have to filter the events for is_global. its just simpler in a single table with active/inactive. Somerthing is to also have an end time the notice is active for, so whem that time is reach it auto hides it.

**Comment by jvasallo** [comment]
We could have a table with a foreign key relationship to a given status?
Something like:

board_alerts
- ID: PK
- Message ID: FK to message
- Status: 0/1
- Level: FK to status (maybe use this for different color background or
  something?) Yellow background means degraded service, red means outage,
  blue means planned?
